//Data Actions
export const FETCH_DATA = 'FETCH_DATA'
export const UPDATE_DATA = 'UPDATE_DATA'
export const SORT_DATA = 'SORT_DATA'
export const FETCH_COMPANY = 'FETCH_COMPANY'

//Filter Actions
export const FILTER_NAME = 'FILTER_NAME'
export const FILTER_DESCRIPTION = 'FILTER_DESCRIPTION'
export const FILTER_DROPDOWNOPTIONS = 'FILTER_DROPDOWNOPTIONS'
export const FILL_COLUMN = 'FILL_COLUMN'
export const FILTER_SLIDERS = 'FILTER_SLIDERS'
export const CLEAR_DROPDOWNOPTIONS = 'CLEAR_DROPDOWNOPTIONS'
export const CLEAR_SLIDERS = 'CLEAR_SLIDERS'
export const CLEAR_ALL = 'CLEAR_ALL'
export const CHANGE_RANK_WEIGHTS = 'CHANGE_RANK_WEIGHTS'

//Page Actions
export const CHANGE_PAGE_NUMBER = 'CHANGE_PAGE_NUMBER'
export const CHANGE_LAST_PAGE_NUMBER = 'CHANGE_LAST_PAGE_NUMBER'

//Other Actions
export const FORMAT_DOLLAR = 'FORMAT_DOLLAR'